import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/nav/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const InstagramSans = localFont({
  src: "./fonts/Instagram Sans/Instagram Sans.ttf",
  variable: "--font-instagram-sans",
});

const InstagramBold = localFont({
  src: "./fonts/Instagram Sans/Instagram Sans Bold.ttf",
  variable: "--font-instagram-bold",
});





export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${InstagramSans.variable} ${InstagramBold.variable}`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
