//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Attractions struct {
	UID                int32 `sql:"primary_key"`
	Tid                int32 `sql:"primary_key"`
	Aid                int32 `sql:"primary_key"`
	AttractionName     string
	AttractionLocation string
}
