//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Tokens struct {
	ID          int32 `sql:"primary_key"`
	BearerToken string
	ExpiryTime  int64
	UID         int32
}
