//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Users struct {
	UID            int32 `sql:"primary_key"`
	Name           string
	Email          string
	HashedPassword string
	Salt           string
	InstagramID    *string
	Verified       bool
}
